// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-9zYKBRiREkPuwSZYAEHEAfTh6NIBlI',
    appId: '1:85646633831:web:396de01f4233d931055dc2',
    messagingSenderId: '85646633831',
    projectId: 'mobile-final-5f008',
    authDomain: 'mobile-final-5f008.firebaseapp.com',
    databaseURL: 'https://mobile-final-5f008-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-final-5f008.firebasestorage.app',
    measurementId: 'G-7WK51E2S5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuPCD8NPNntFUYy1LUA2Jk-pZYCLsBjU',
    appId: '1:85646633831:android:8fa7bcd2ebfde632055dc2',
    messagingSenderId: '85646633831',
    projectId: 'mobile-final-5f008',
    databaseURL: 'https://mobile-final-5f008-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-final-5f008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1pUgyP3BG2rxq0n0U1FpgLmDXMUsY84',
    appId: '1:85646633831:ios:d748e9e32eb69774055dc2',
    messagingSenderId: '85646633831',
    projectId: 'mobile-final-5f008',
    databaseURL: 'https://mobile-final-5f008-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-final-5f008.firebasestorage.app',
    iosClientId: '85646633831-c66qt4jah2tuh4l2rr9qkkk2de5v49db.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1pUgyP3BG2rxq0n0U1FpgLmDXMUsY84',
    appId: '1:85646633831:ios:d748e9e32eb69774055dc2',
    messagingSenderId: '85646633831',
    projectId: 'mobile-final-5f008',
    databaseURL: 'https://mobile-final-5f008-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-final-5f008.firebasestorage.app',
    iosClientId: '85646633831-c66qt4jah2tuh4l2rr9qkkk2de5v49db.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY-9zYKBRiREkPuwSZYAEHEAfTh6NIBlI',
    appId: '1:85646633831:web:15aeef4368d76cad055dc2',
    messagingSenderId: '85646633831',
    projectId: 'mobile-final-5f008',
    authDomain: 'mobile-final-5f008.firebaseapp.com',
    databaseURL: 'https://mobile-final-5f008-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-final-5f008.firebasestorage.app',
    measurementId: 'G-2HWFSRB34T',
  );
}
